"""empty message

Revision ID: 5b8631c25a7b
Revises: 18696ac5602a
Create Date: 2022-08-26 14:26:49.015739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8631c25a7b'
down_revision = '18696ac5602a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('body', sa.String(length=140), nullable=True))
    op.drop_column('address', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('address', 'body')
    # ### end Alembic commands ###
